security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        #- { path: ^/moto/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
        #- { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }0
        - { path: ^/vehiculo/.*, role: [IS_AUTHENTICATED_FULLY] }
        - { path: ^/gasto/.*, role: [IS_AUTHENTICATED_FULLY] }
        - { path: ^/gasolina/.*, role: [IS_AUTHENTICATED_FULLY] }
        
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
