txinbometro_vehiculo:
    resource: "@TxinbometroBundle/Resources/config/routing/vehiculo.yml"
    prefix:   /vehiculo

txinbometro_gasolina:
    resource: "@TxinbometroBundle/Resources/config/routing/gasolina.yml"
    prefix:   /gasolina
    
txinbometro_gasto:
    resource: "@TxinbometroBundle/Resources/config/routing/gasto.yml"
    prefix:   /gasto
 
txinbometro_estadisticas:
    resource: "@TxinbometroBundle/Resources/config/routing/estadisticas.yml"
    prefix:   /estadisticas 
    

#acceder:
#    pattern:  /acceder
#    defaults: { _controller: TxinbometroBundle:Default:acceder }