txinbometro_vehiculo:
    pattern:  /
    defaults: { _controller: "TxinbometroBundle:Vehiculo:index" }

txinbometro_vehiculo_show:
    pattern:  /{id}/show
    defaults: { _controller: "TxinbometroBundle:Vehiculo:show" }

txinbometro_vehiculo_new:
    pattern:  /new
    defaults: { _controller: "TxinbometroBundle:Vehiculo:new" }

txinbometro_vehiculo_create:
    pattern:  /create
    defaults: { _controller: "TxinbometroBundle:Vehiculo:create" }
    requirements: { _method: post }

txinbometro_vehiculo_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TxinbometroBundle:Vehiculo:edit" }

txinbometro_vehiculo_update:
    pattern:  /{id}/update
    defaults: { _controller: "TxinbometroBundle:Vehiculo:update" }
    requirements: { _method: post }

txinbometro_vehiculo_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TxinbometroBundle:Vehiculo:delete" }
    requirements: { _method: post }

txinbometro_vehiculo_select:
    pattern:  /{id}/select
    defaults: { _controller: "TxinbometroBundle:Vehiculo:select" }
    requirements: { _method: get }
    
txinbometro_vehiculo_cargar:
    pattern: /cargar
    defaults: { _controller: "TxinbometroBundle:Vehiculo:cargar" }