<?php

namespace DS\TxinbometroBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GasolinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GasolinaRepository extends EntityRepository
{
    public function getAllFrom($vehiculo_id) {
        return $this->_em->createQuery('SELECT g FROM TxinbometroBundle:Gasolina g WHERE g.vehiculo = '.$vehiculo_id.' ORDER BY g.km')->getResult();
    }        
}