<?php

namespace DS\TxinbometroBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GasolinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GasolinaRepository extends EntityRepository
{
}