<?php

namespace DS\TxinbometroBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GastoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GastoRepository extends EntityRepository
{
    public function getAllFrom($usuario_id) {
        return $this->_em->createQuery('SELECT g FROM TxinbometroBundle:Gasto g WHERE g.vehiculo = '.$usuario_id)->getResult();
    }    
}