<?php

namespace Dafuer\TxinbometroBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoRepository extends EntityRepository {

    public function getAllFrom($usuario_id) {
        return $this->_em->createQuery('SELECT v FROM TxinbometroBundle:Vehiculo v WHERE v.usuario = '.$usuario_id)->getResult();
    }


}