txinbometro_gasto:
    pattern:  /
    defaults: { _controller: "TxinbometroBundle:Gasto:index" }

txinbometro_gasto_show:
    pattern:  /{id}/show
    defaults: { _controller: "TxinbometroBundle:Gasto:show" }

txinbometro_gasto_new:
    pattern:  /new
    defaults: { _controller: "TxinbometroBundle:Gasto:new" }

txinbometro_gasto_create:
    pattern:  /create
    defaults: { _controller: "TxinbometroBundle:Gasto:create" }
    requirements: { _method: post }

txinbometro_gasto_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TxinbometroBundle:Gasto:edit" }

txinbometro_gasto_update:
    pattern:  /{id}/update
    defaults: { _controller: "TxinbometroBundle:Gasto:update" }
    requirements: { _method: post }

txinbometro_gasto_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TxinbometroBundle:Gasto:delete" }
    requirements: { _method: post }
