    
txinbometro_graficos_consumogeneralkm:
    pattern:  /graph
    defaults: { _controller: "TxinbometroBundle:Graficos:consumogeneralkm" }
    
txinbometro_graficos_comparativauso:
    pattern:  /comparativauso
    defaults: { _controller: "TxinbometroBundle:Graficos:comparativauso" }
    
txinbometro_graficos_usomensual:
    pattern:  /usomensual
    defaults: { _controller: "TxinbometroBundle:Graficos:usomensual" }
    
txinbometro_graficos_comparativaeconomica:
    pattern:  /comparativaeconomica
    defaults: { _controller: "TxinbometroBundle:Graficos:comparativaeconomica" }

