vehiculo:
    pattern:  /
    defaults: { _controller: "TxinbometroBundle:Vehiculo:index" }

vehiculo_show:
    pattern:  /{id}/show
    defaults: { _controller: "TxinbometroBundle:Vehiculo:show" }

vehiculo_new:
    pattern:  /new
    defaults: { _controller: "TxinbometroBundle:Vehiculo:new" }

vehiculo_create:
    pattern:  /create
    defaults: { _controller: "TxinbometroBundle:Vehiculo:create" }
    requirements: { _method: post }

vehiculo_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TxinbometroBundle:Vehiculo:edit" }

vehiculo_update:
    pattern:  /{id}/update
    defaults: { _controller: "TxinbometroBundle:Vehiculo:update" }
    requirements: { _method: post }

vehiculo_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TxinbometroBundle:Vehiculo:delete" }
    requirements: { _method: post }

vehiculo_select:
    pattern:  /{id}/select
    defaults: { _controller: "TxinbometroBundle:Vehiculo:select" }
    requirements: { _method: get }